import type {
  BidCostScenario,
  EconomicCategory,
  EconomicFrequency,
  EconomicProvider,
  IndicatorCatalogItem,
} from '../../src/types/index.ts';

export const VERIFIED_AT = '2026-08-20';

export interface CatalogSeed extends IndicatorCatalogItem {}

export const MVP_CATALOG: CatalogSeed[] = [
  {
    indicatorKey: 'ppi',
    provider: 'ECOS',
    displayNameKo: '생산자물가지수(총지수)',
    category: 'inflation',
    frequency: 'monthly',
    unit: '2020=100',
    mapping: {
      statisticTableCode: '404Y014',
      statisticTableName: '4.1.1.1. 생산자물가지수(기본분류)',
      itemCode: '*AA',
      itemName: '총지수',
      cycle: 'M',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'cpi',
    provider: 'ECOS',
    displayNameKo: '소비자물가지수(총지수)',
    category: 'inflation',
    frequency: 'monthly',
    unit: '2020=100',
    mapping: {
      statisticTableCode: '901Y009',
      statisticTableName: '4.2.1. 소비자물가지수',
      itemCode: '0',
      itemName: '총지수',
      cycle: 'M',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'usd_krw',
    provider: 'ECOS',
    displayNameKo: '원/달러 환율(매매기준율)',
    category: 'fx',
    frequency: 'daily',
    unit: '원',
    currency: 'USD',
    mapping: {
      statisticTableCode: '731Y001',
      statisticTableName: '3.1.1.1. 주요국 통화의 대원화환율',
      itemCode: '0000001',
      itemName: '원/미국달러(매매기준율)',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'jpy_krw',
    provider: 'ECOS',
    displayNameKo: '원/엔(100엔)',
    category: 'fx',
    frequency: 'daily',
    unit: '원',
    currency: 'JPY',
    mapping: {
      statisticTableCode: '731Y001',
      statisticTableName: '3.1.1.1. 주요국 통화의 대원화환율',
      itemCode: '0000002',
      itemName: '원/일본엔(100엔)',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'eur_krw',
    provider: 'ECOS',
    displayNameKo: '원/유로',
    category: 'fx',
    frequency: 'daily',
    unit: '원',
    currency: 'EUR',
    mapping: {
      statisticTableCode: '731Y001',
      statisticTableName: '3.1.1.1. 주요국 통화의 대원화환율',
      itemCode: '0000003',
      itemName: '원/유로',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'cny_krw',
    provider: 'ECOS',
    displayNameKo: '원/위안 환율(매매기준율)',
    category: 'fx',
    frequency: 'daily',
    unit: '원',
    currency: 'CNY',
    mapping: {
      statisticTableCode: '731Y001',
      statisticTableName: '3.1.1.1. 주요국 통화의 대원화환율',
      itemCode: '0000053',
      itemName: '원/위안(매매기준율)',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'base_rate',
    provider: 'ECOS',
    displayNameKo: '한국은행 기준금리',
    category: 'interest_rate',
    frequency: 'daily',
    unit: '연%',
    mapping: {
      statisticTableCode: '722Y001',
      statisticTableName: '1.3.1. 한국은행 기준금리 및 여수신금리',
      itemCode: '0101000',
      itemName: '한국은행 기준금리',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'cd_91',
    provider: 'ECOS',
    displayNameKo: 'CD(91일)',
    category: 'interest_rate',
    frequency: 'daily',
    unit: '연%',
    mapping: {
      statisticTableCode: '817Y002',
      statisticTableName: '1.3.2.1. 시장금리(일별)',
      itemCode: '010502000',
      itemName: 'CD(91일)',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'tbond_3y',
    provider: 'ECOS',
    displayNameKo: '국고채(3년)',
    category: 'interest_rate',
    frequency: 'daily',
    unit: '연%',
    mapping: {
      statisticTableCode: '817Y002',
      statisticTableName: '1.3.2.1. 시장금리(일별)',
      itemCode: '010200000',
      itemName: '국고채(3년)',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'corp_aa_3y',
    provider: 'ECOS',
    displayNameKo: '회사채(3년, AA-)',
    category: 'interest_rate',
    frequency: 'daily',
    unit: '연%',
    mapping: {
      statisticTableCode: '817Y002',
      statisticTableName: '1.3.2.1. 시장금리(일별)',
      itemCode: '010300000',
      itemName: '회사채(3년, AA-)',
      cycle: 'D',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'import_price',
    provider: 'ECOS',
    displayNameKo: '수입물가지수(총지수)',
    category: 'steel_proxy',
    frequency: 'monthly',
    unit: '2020=100',
    mapping: {
      statisticTableCode: '401Y015',
      statisticTableName: '4.3.2.1. 수입물가지수(기본분류)',
      itemCode: '*AA',
      itemName: '총지수',
      cycle: 'M',
    },
    sourceUrl: 'https://ecos.bok.or.kr/api/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'wti',
    provider: 'EIA',
    displayNameKo: 'WTI 원유 현물',
    category: 'energy',
    frequency: 'daily',
    unit: 'USD/bbl',
    currency: 'USD',
    mapping: {
      route: 'petroleum/pri/spt',
      frequency: 'daily',
      dataField: 'value',
      facets: { series: ['RWTC'] },
    },
    sourceUrl: 'https://www.eia.gov/opendata/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'brent',
    provider: 'EIA',
    displayNameKo: 'Brent 원유 현물',
    category: 'energy',
    frequency: 'daily',
    unit: 'USD/bbl',
    currency: 'USD',
    mapping: {
      route: 'petroleum/pri/spt',
      frequency: 'daily',
      dataField: 'value',
      facets: { series: ['RBRTE'] },
    },
    sourceUrl: 'https://www.eia.gov/opendata/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'natgas',
    provider: 'EIA',
    displayNameKo: '천연가스(Henry Hub)',
    category: 'energy',
    frequency: 'daily',
    unit: 'USD/MMBtu',
    currency: 'USD',
    mapping: {
      route: 'natural-gas/pri/fut',
      frequency: 'daily',
      dataField: 'value',
      facets: { series: ['RNGWHHD'] },
    },
    sourceUrl: 'https://www.eia.gov/opendata/',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'copper',
    provider: 'IMF',
    displayNameKo: '구리(Copper)',
    category: 'nonferrous_metal',
    frequency: 'monthly',
    unit: 'USD/mt',
    currency: 'USD',
    mapping: {
      dataset: 'PCPS',
      agency: 'IMF.RES',
      country: 'G001',
      indicator: 'PCOPP',
      transformation: 'USD',
      frequency: 'M',
      seriesKey: 'G001.PCOPP.USD.M',
      indicatorName: 'Copper, US dollars per metric tonne, Unit prices',
    },
    sourceUrl: 'https://data.imf.org/Datasets/PCPS',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'aluminum',
    provider: 'IMF',
    displayNameKo: '알루미늄(Aluminum)',
    category: 'nonferrous_metal',
    frequency: 'monthly',
    unit: 'USD/mt',
    currency: 'USD',
    mapping: {
      dataset: 'PCPS',
      agency: 'IMF.RES',
      country: 'G001',
      indicator: 'PALUM',
      transformation: 'USD',
      frequency: 'M',
      seriesKey: 'G001.PALUM.USD.M',
      indicatorName: 'Aluminum, US dollars per metric tonne, Unit prices',
    },
    sourceUrl: 'https://data.imf.org/Datasets/PCPS',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'nickel',
    provider: 'IMF',
    displayNameKo: '니켈(Nickel)',
    category: 'nonferrous_metal',
    frequency: 'monthly',
    unit: 'USD/mt',
    currency: 'USD',
    mapping: {
      dataset: 'PCPS',
      agency: 'IMF.RES',
      country: 'G001',
      indicator: 'PNICK',
      transformation: 'USD',
      frequency: 'M',
      seriesKey: 'G001.PNICK.USD.M',
      indicatorName: 'Nickel, US dollars per metric tonne, Unit prices',
    },
    sourceUrl: 'https://data.imf.org/Datasets/PCPS',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
  {
    indicatorKey: 'zinc',
    provider: 'IMF',
    displayNameKo: '아연(Zinc)',
    category: 'nonferrous_metal',
    frequency: 'monthly',
    unit: 'USD/mt',
    currency: 'USD',
    mapping: {
      dataset: 'PCPS',
      agency: 'IMF.RES',
      country: 'G001',
      indicator: 'PZINC',
      transformation: 'USD',
      frequency: 'M',
      seriesKey: 'G001.PZINC.USD.M',
      indicatorName: 'Zinc, US dollars per metric tonne, Unit prices',
    },
    sourceUrl: 'https://data.imf.org/Datasets/PCPS',
    active: true,
    verifiedAt: VERIFIED_AT,
  },
];

export const CORE_INDICATOR_KEYS = [
  'ppi',
  'cpi',
  'usd_krw',
  'base_rate',
  'cd_91',
  'tbond_3y',
  'corp_aa_3y',
  'wti',
  'brent',
  'natgas',
  'copper',
  'aluminum',
  'nickel',
  'zinc',
];

export const DEFAULT_BID_SCENARIO: BidCostScenario = {
  id: 'default',
  name: '기본 입찰 원가 시나리오',
  baseCost: 1_000_000_000,
  baseFx: null,
  weights: [
    { id: 'steel', name: '철강', weightPct: 35, indicatorKeys: ['ppi', 'import_price'], fxKey: 'usd_krw' },
    { id: 'aluminum', name: '알루미늄', weightPct: 8, indicatorKeys: ['aluminum'], fxKey: 'usd_krw' },
    { id: 'copper', name: '구리', weightPct: 7, indicatorKeys: ['copper'], fxKey: 'usd_krw' },
    { id: 'import', name: '수입부품', weightPct: 15, indicatorKeys: ['import_price'], fxKey: 'usd_krw' },
    { id: 'energy', name: '에너지', weightPct: 10, indicatorKeys: ['wti'] },
    { id: 'labor', name: '인건비', weightPct: 15, indicatorKeys: ['cpi'] },
    { id: 'finance', name: '금융비용', weightPct: 5, indicatorKeys: ['corp_aa_3y'] },
    { id: 'other', name: '기타', weightPct: 5, indicatorKeys: ['cpi'] },
  ],
  riskWeights: {
    costChange: 0.4,
    inflation: 0.2,
    fx: 0.2,
    energy: 0.1,
    rates: 0.1,
  },
};

export function providerLabel(provider: EconomicProvider): string {
  if (provider === 'ECOS') return 'Bank of Korea ECOS';
  if (provider === 'EIA') return 'U.S. EIA';
  return 'IMF PCPS';
}

export function asCategory(value: string): EconomicCategory {
  return value as EconomicCategory;
}

export function asFrequency(value: string): EconomicFrequency {
  if (value === 'daily' || value === 'monthly') return value;
  return 'other';
}

export function asProvider(value: string): EconomicProvider {
  return value as EconomicProvider;
}
